import type { Metadata } from "next";
import Link from "next/link";
import { ContactForm } from "@/components/ContactForm";
import { PageHero } from "@/components/PageHero";
import { StructuredData } from "@/components/StructuredData";
import { site } from "@/lib/site";

export const metadata: Metadata = { title:"Contacto · Horarios y ubicación en Madrid",description:"Contacta con el Centro Evangelístico Solamente Cree. Domingos 11:00h en C.C. Las Rosas, CINESA Sala 7, Madrid. WhatsApp, email y formulario.",alternates:{canonical:"/contacto"},openGraph:{title:"Contacto y ubicación | Solamente Cree",description:"Horarios, ubicación y atención pastoral en Madrid.",url:"/contacto"} };
const faqs=[
 ["¿Dónde está ubicado el Centro Evangelístico Solamente Cree en Madrid?","Nos reunimos en el Centro Comercial Las Rosas, Sala 7 de CINESA, Avenida de Guadalajara 2, 28032 Madrid."],
 ["¿A qué hora son las reuniones y cultos dominicales?","El culto principal se celebra todos los domingos a las 11:00h. La recepción comienza a las 10:30h."],
 ["¿Cómo puedo llegar en transporte público?","La estación de Metro Alsacia, Línea 2, está junto al centro comercial. También llegan las líneas de autobús 70, 106, 140, E2 y N7."],
 ["¿Puedo solicitar una oración por WhatsApp?","Sí. Puedes escribir al +34 687 43 10 33 para enviar tu petición o consultar con el equipo pastoral."]
];
export default function Contacto(){return <main><PageHero eyebrow="Estamos cerca de ti" title="Contacto y Atención Pastoral" text="Escríbenos, consulta cómo llegar o envía tu petición de oración. Nuestro canal directo de WhatsApp está disponible para facilitar el contacto."><a className="btn btn-whatsapp" href={`${site.whatsapp}?text=Hola,%20quisiera%20recibir%20atención%20pastoral`} target="_blank" rel="noreferrer">Iniciar chat en WhatsApp</a></PageHero>
<StructuredData data={{"@context":"https://schema.org","@type":"ContactPage",name:"Contacto Solamente Cree",url:`${site.url}/contacto`,mainEntity:{"@id":`${site.url}/#church`}}}/>
<StructuredData data={{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}}/>
<section className="section"><div className="container contact-layout"><div><span className="eyebrow">Datos de contacto</span><h2>Información directa</h2><div className="contact-cards"><article><strong>Teléfono y WhatsApp</strong><a href={`tel:${site.phone}`}>{site.phoneDisplay}</a></article><article><strong>Correo electrónico</strong><a href={`mailto:${site.email}`}>{site.email}</a></article><article><strong>Sede de cultos</strong><span>{site.address}</span></article><article><strong>Horario principal</strong><span>Domingos a las 11:00h · recepción desde las 10:30h</span></article></div><a className="text-link" href="https://maps.google.com/?q=Av.+de+Guadalajara+2,+28032+Madrid" target="_blank" rel="noreferrer">Abrir ubicación en Google Maps →</a></div><div className="form-panel"><h2>Envíanos un mensaje</h2><p>El formulario está preparado para enviar a un webhook configurable mediante variable de entorno.</p><ContactForm /></div></div></section>
<section className="section section-soft"><div className="container"><div className="section-heading"><span className="eyebrow">Cómo llegar</span><h2>Culto dominical en Las Rosas, Madrid</h2></div><div className="location-grid"><article><h3>Metro</h3><p>Alsacia · Línea 2, a pocos minutos a pie.</p></article><article><h3>Autobús</h3><p>Líneas EMT 70, 106, 140, E2 y N7.</p></article><article><h3>Coche</h3><p>Aparcamiento del Centro Comercial Las Rosas.</p></article></div></div></section>
<section className="section"><div className="container narrow"><div className="section-heading"><span className="eyebrow">Preguntas frecuentes</span><h2>Antes de visitarnos</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===1}><summary>{q}<span>＋</span></summary><p>{a}</p></details>)}</div><div className="center-link"><Link href="/servicios" className="text-link">Conocer todos nuestros servicios →</Link></div></div></section></main>}
