import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "@/components/PageHero";
import { images, site } from "@/lib/site";

export const metadata: Metadata = { title:"Sobre Nosotros · Manuel y Toñy",description:"Conoce el Centro Evangelístico Solamente Cree, su visión, comunidad y la trayectoria ministerial del Apóstol Manuel Ramírez de Arellano y Toñy.",alternates:{canonical:"/sobre-nosotros"},openGraph:{title:"Sobre Nosotros | Solamente Cree",description:"Historia, visión y liderazgo del Centro Evangelístico Solamente Cree en Madrid.",url:"/sobre-nosotros"} };
export default function SobreNosotros(){return <main><PageHero eyebrow="Nuestra comunidad de fe" title="Sobre Nosotros" text="Una iglesia evangélica en Madrid orientada a la fe, la adoración, la enseñanza bíblica y el acompañamiento de personas y familias." />
<section className="section"><div className="container split"><div><span className="eyebrow">Quiénes somos</span><h2>Tu Iglesia Evangélica y Centro de Fe en Madrid</h2><p>El <strong>Centro Evangelístico Solamente Cree</strong> nació con el propósito de anunciar el Evangelio de Jesucristo con poder, amor y una comunidad abierta. Creemos que la Iglesia no es únicamente un edificio, sino una familia de fe activa donde cada persona puede encontrar acogida, restauración y comunión.</p><p>Guiados por una convicción bíblica, nuestras reuniones dominicales en Madrid combinan adoración, enseñanza y acompañamiento pastoral. Buscamos crear un entorno donde cada persona pueda crecer espiritualmente y vivir su fe de una manera práctica.</p></div><div className="image-frame portrait"><Image src={images.pastors} alt="Apóstol Manuel Ramírez de Arellano y Toñy, fundadores de Solamente Cree" fill sizes="(max-width:900px) 100vw, 40vw" priority/></div></div></section>
<section className="section section-soft"><div className="container"><div className="section-heading"><span className="eyebrow">Nuestros valores</span><h2>Fe viva, comunidad y avivamiento</h2></div><div className="cards three"><article className="card"><span className="card-icon">✦</span><h3>Fe Viva e Inquebrantable</h3><p>Confiamos en las promesas bíblicas y en una fe que se expresa en la vida cotidiana.</p><blockquote>«Al que cree, todo le es posible» · Marcos 9:23</blockquote></article><article className="card"><span className="card-icon">♡</span><h3>Amor y Comunidad Genuina</h3><p>Una congregación de brazos abiertos donde cada persona puede encontrar acompañamiento y un nuevo comienzo.</p><blockquote>«En esto conocerán todos que sois mis discípulos» · Juan 13:35</blockquote></article><article className="card"><span className="card-icon">✧</span><h3>Poder y Avivamiento</h3><p>Adoración, predicación y oración como parte central de nuestra experiencia congregacional.</p><blockquote>«Con señales y prodigios» · Romanos 15:19</blockquote></article></div></div></section>
<section className="section"><div className="container split"><div className="media-stack"><div className="image-frame landscape"><Image src={images.worship} alt="Culto dominical en Solamente Cree" fill sizes="(max-width:900px) 100vw, 48vw"/></div><div className="image-frame landscape small"><Image src={images.preaching} alt="Manuel y Toñy durante una predicación" fill sizes="(max-width:900px) 100vw, 48vw"/></div></div><div><span className="eyebrow">Liderazgo y trayectoria</span><h2>Manuel y Toñy · Ministerio Apostólico y Alabanza</h2><p>El Apóstol Manuel Ramírez de Arellano y su esposa Toñy cuentan con décadas de trayectoria ministerial en España, Europa y América Latina. Su labor reúne evangelismo, pastoreo, música y producción audiovisual cristiana.</p><p>Juntos han desarrollado el ministerio musical <strong>Manuel y Toñy</strong> y <strong>Dejan2huella Producciones</strong>. Actualmente pastorean el Centro Evangelístico Solamente Cree en Madrid, acompañando a familias, jóvenes y creyentes que desean crecer en su fe.</p><a className="btn btn-whatsapp" href={`${site.whatsapp}?text=Hola,%20quisiera%20información%20sobre%20Solamente%20Cree`} target="_blank" rel="noreferrer">Hablar con el equipo pastoral</a></div></div></section></main>}
