import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "@/components/PageHero";
import { images, site } from "@/lib/site";

export const metadata: Metadata = { title:"Proyectos · Manuel y Toñy y Dejan2huella",description:"Proyectos de Manuel y Toñy y Dejan2huella Producciones: alabanza, mensajes, multimedia y testimonios vinculados al Centro Evangelístico Solamente Cree.",alternates:{canonical:"/proyectos"},openGraph:{title:"Proyectos y multimedia | Solamente Cree",description:"Alabanza, mensajes y contenidos de Dejan2huella Producciones.",url:"/proyectos"} };
const testimonials=[
  {title:"Sanidad Total de Cáncer Diagnosticado",name:"María Elena G.",place:"Madrid",text:"Los médicos no me daban esperanzas. En el culto oraron por mí creyendo que para Dios nada es imposible. En mi siguiente resonancia no encontraron rastro del tumor."},
  {title:"Matrimonio y Hogar Restaurado",name:"Carlos y Rocío M.",place:"Alcalá de Henares",text:"Llegamos a la iglesia en un momento muy difícil. La palabra y el acompañamiento pastoral nos ayudaron a restaurar nuestra relación y hoy caminamos juntos en la fe."},
  {title:"Liberación y Paz Inexplicable",name:"Javier S.",place:"Madrid",text:"Después de años de ansiedad encontré un espacio de fe, oración y acompañamiento. Desde entonces vivo este proceso con una paz que antes no conocía."}
];
export default function Proyectos(){return <main><PageHero eyebrow="Producciones & mensajes" title="Proyectos, alabanza y multimedia" text="Una selección de los contenidos y líneas ministeriales desarrolladas por Manuel y Toñy y Dejan2huella Producciones."><a className="btn btn-gold" href={site.social.youtube} target="_blank" rel="noreferrer">Visitar YouTube</a></PageHero>
<section className="section"><div className="container split"><div className="image-frame landscape featured"><Image src={images.multimedia} alt="Noches de adoración y milagros con Manuel y Toñy" fill sizes="(max-width:900px) 100vw, 55vw" priority/></div><div><span className="eyebrow">Proyecto destacado</span><h2>Noches de Adoración y Milagros</h2><p>Contenido audiovisual centrado en adoración, predicación y mensajes de fe, producido bajo la identidad de Dejan2huella.</p><p>El proyecto digital permite prolongar durante la semana el contenido compartido en la vida ministerial y acercarlo a personas fuera de Madrid.</p><a className="text-link" href={site.social.youtube} target="_blank" rel="noreferrer">Ver contenidos en YouTube →</a></div></div></section>
<section className="section section-soft"><div className="container"><div className="section-heading"><span className="eyebrow">Líneas de trabajo</span><h2>Ministerio, música y comunicación</h2></div><div className="project-grid"><article className="project-card"><div className="image-frame landscape"><Image src={images.production} alt="Producción de alabanza de Manuel y Toñy" fill sizes="(max-width:900px) 100vw, 33vw"/></div><h3>Dejan2huella Producciones</h3><p>Producción musical y audiovisual cristiana vinculada a Manuel y Toñy.</p></article><article className="project-card"><div className="image-frame landscape"><Image src={images.preaching} alt="Predicación de Manuel y Toñy en Solamente Cree" fill sizes="(max-width:900px) 100vw, 33vw"/></div><h3>Mensajes de Fe</h3><p>Predicaciones, reflexiones y recursos para acompañar la vida espiritual.</p></article><article className="project-card"><div className="image-frame landscape"><Image src={images.community} alt="Comunidad de fe del Centro Evangelístico Solamente Cree" fill sizes="(max-width:900px) 100vw, 33vw"/></div><h3>Comunidad Solamente Cree</h3><p>Encuentros presenciales de adoración, oración y vida congregacional en Madrid.</p></article></div></div></section>
<section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Testimonios</span><h2>Historias compartidas por la comunidad</h2><p>Historias compartidas en el material original de la web.</p></div><div className="cards three">{testimonials.map(t=><article className="card testimonial" key={t.title}><div className="stars" aria-label="Testimonio">★★★★★</div><h3>{t.title}</h3><p>«{t.text}»</p><footer><strong>{t.name}</strong><span>{t.place}</span></footer></article>)}</div></div></section></main>}
